[package]
name = "ousagi"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tokio = { version = "1.53.1", features = ["full"] }
bytes = "1.12.1"
criterion = { version = "0.8.2", features = ["async_tokio", "html_reports"] }
rand = { version = "0.8.7", features = ["small_rng"] }

[[bench]]
name = "throughput"
harness = false
