[package]
name = "ousagi"
version = "0.1.8"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tokio = { version = "1.53.1", features = ["full"] }
bytes = "1.12.1"
itoa = "1.0.18"
dashmap = "6.2.1"
atoi = "3.1.0"
memchr = "2.8.3"

[dev-dependencies]
criterion = {version="0.8.2", features=["html_reports", "async_tokio"]}

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.bench]
inherits = "release"
debug = true
strip = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "connection"
harness = false
