[package]
name = "ousagi"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tokio = { version = "1.53.1", features = ["full"] }
bytes = "1.12.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
# panic = "abort"
strip = true

[profile.bench]
inherits = "release"
debug = true
